#define CONFIG_HOUR_HAND_LENGTH 19.0f
#define CONFIG_MINUTE_HAND_LENGTH 21.0f
#define CONFIG_HAND_WIDTH 7.0f

#define CONFIG_HAND_COLOR_R 1.0f
#define CONFIG_HAND_COLOR_G 1.0f
#define CONFIG_HAND_COLOR_B 1.0f
#define CONFIG_HAND_COLOR_A 1.0f
